### ISSUE TITLE
Aspose-Dynamics365-SharePoint-PowerApps

### ISSUE THREAD

**Issue by w3bt03d** [aspose-free-consulting/projects#103]
I need help building an app that would allow users to upload PDF files to convert into JPG. I would like to use power apps where the user has a button to upload documents (*.pdf), a button to convert to *.jpg, and a button to download the converted file from the application. 

Flow: 
User(s) uploads PDF file(s) using application
Aspose converts to JPG
User(s) downloads converted file
User(s) uploads into Dynamics 365

**Comment by asadalikhan90** [comment]
@w3bt03d 

You can use Aspose.PDF for .NET in the code behind in order to convert PDF (FileStream) into a JPG Image (Stream). The conversion functionality can be carried out using the following simple code snippet:

```
var fs = new FileStream(dataDir + "input.pdf", FileMode.Open);
Document pdfDocument = new Document(fs);
foreach (Page page in pdfDocument.Pages)
{
 using (FileStream imageStream = new FileStream(dataDir + "image" + page.Number + ".jpg", FileMode.Create))
 {
 Resolution resolution = new Resolution(300);
 JpegDevice jpegDeviceLarge = new JpegDevice(resolution, 100);
 jpegDeviceLarge.RenderingOptions.InterpolationHighQuality = true;
 jpegDeviceLarge.RenderingOptions.UseNewImagingEngine = true;
 jpegDeviceLarge.Process(page, imageStream);
 }
}
```

You may please try using the above code snippet in your application and let us know if you have further requirements. Also, if you are interested in using Aspose.PDF for SharePoint specifically, please create a post in our [support forum](https://forum.aspose.com/c/pdf). The support of Office 365 SharePoint Online is yet to be implemented and the progress against it can be tracked appropriately in the support forum.
