### ISSUE TITLE
Use Aspose products (PDF, Slides, Words, Cells) to generate HTML version of PDF, PPT, PPTX, DOC, DOCX, XLS, XLSX documents resulting in a single Aspose HTML file for each document processed. Each Aspose file would combine the HTML, Javascript, and CSS.

### ISSUE THREAD

**Issue by jjacks72** [aspose-free-consulting/projects#109]
Our goal is to show a preview of documents on our web application (built on React) that highlights search terms in the document.

We would like to use Aspose products (PDF, Slides, Words, Cells) to generate HTML version of PDF, PPT, PPTX, DOC, DOCX, XLS, XLSX documents. HTML version of the document is used to show the preview of the document and highlight the terms using JavaScript.

Our questions:
o	After reviewing the demo, we see that, Aspose products (PDF, Slides, Words, Cells) are generating a folder which contains CSS, JS and HTML files individually. Is it possible to generate one HTML file per document?
o	Is there any better way that we can solve our problem statement other than what we are considering using Aspose products (PDF, Slides, Words, Cells)?

Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by shahzad-latif** [comment]
@jjacks72 

Thanks for sharing your requirements. We'll provide you a detailed reply with required resources shortly.

**Comment by asadalikhan90** [comment]
@jjacks72 

You can surely use Aspose APIs in your application code-behind in order to implement your requirements (i.e. Convert Documents to HTML). We have also showcased this feature and implementation on our Free Online Apps Service (https://products.aspose.app). The source code used behind these apps is also available over GitHub to provide complete guidance on how to use Aspose APIs in application code-behind to implement the required functionality. You may please explore the below links for more information:

* [Presentation to HTML Online Converter](https://products.aspose.app/slides/conversion) | [Source Code](https://github.com/aspose-slides/Aspose.Slides-for-.NET/tree/master/Demos/src/Aspose.Slides.Live.Demos.UI/Views/Conversion)
* [Word to HTML Online Converter](https://products.aspose.app/words/conversion) | [Source Code](https://github.com/aspose-words/Aspose.Words-for-.NET/tree/master/Demos/src/Aspose.Words.Live.Demos.UI/Views/Conversion)
* [Excel to HTML Online Converter](https://products.aspose.app/cells/conversion) | [Source Code](https://github.com/aspose-cells/Aspose.Cells-for-.NET/blob/master/Demos/Aspose.Cells.UI/Views/Cells/Conversion.cshtml)
* [PDF to HTML Online Converter](https://products.aspose.app/pdf/conversion) | [Source Code](https://github.com/aspose-pdf/Aspose.PDF-for-.NET/tree/master/Demos/src/Aspose.PDF.Live.Demos.UI/Views/Conversion)

> After reviewing the demo, we see that, Aspose products (PDF, Slides, Words, Cells) are generating a folder which contains CSS, JS and HTML files individually. Is it possible to generate one HTML file per document?

We need to further check and investigate this requirement of yours and we request you please create a post in our [**official support forum**](https://forum.aspose.com/c/total/7) where your concerns could be addressed accordingly. At the moment, we can however suggest a workaround to convert the documents into PDF and then generate a single HTML file with all resources using Aspose.PDF because the API does offer a feature to export PDF to a single HTML file. Please check the below documentation articles for more information:

* [Convert Word to PDF](https://docs.aspose.com/words/net/convert-a-document-to-pdf/)
* [Convert Excel to PDF](https://docs.aspose.com/cells/net/convert-excel-workbook-to-pdf/)
* [Convert PPT/PPTX to PDF](https://docs.aspose.com/slides/net/convert-powerpoint-ppt-and-pptx-to-pdf/)
* Convert PDF to Single HTML file using **Aspose.PDF for .NET**

```
Document doc = new Document(dataDir + "source.pdf");
HtmlSaveOptions newOptions = new HtmlSaveOptions();
// this is usage of tested feature
newOptions.PartsEmbeddingMode = HtmlSaveOptions.PartsEmbeddingModes.EmbedAllIntoHtml;
// this is just optimozation for IE and can be omitted
newOptions.LettersPositioningMethod = HtmlSaveOptions.LettersPositioningMethods.UseEmUnitsAndCompensationOfRoundingErrorsInCss;
newOptions.RasterImagesSavingMode = HtmlSaveOptions.RasterImagesSavingModes.AsEmbeddedPartsOfPngPageBackground;
newOptions.FontSavingMode = HtmlSaveOptions.FontSavingModes.SaveInAllFormats;
newOptions.RemoveEmptyAreasOnTopAndBottom = true;
string outHtmlFile = dataDir + @"output.html";
doc.Save(outHtmlFile, newOptions);
```

> Is there any better way that we can solve our problem statement other than what we are considering using Aspose products (PDF, Slides, Words, Cells)?

You can please obtain a [30-days free temporary license](https://purchase.aspose.com/temporary-license) in order to evaluate Aspose APIs in their full capacity and decide accordingly. In case you face any issue or need any kind of assistance related to Aspose APIs, please feel free to let us know by creating a topic in our [**official support forum**](https://forum.aspose.com/c/total/7) where you will be assisted accordingly.
