### ISSUE TITLE
I want to create/build Demo project for my client to convert JSON into PDF and WORD

### ISSUE THREAD

**Issue by ranjeetsinghr** [aspose-free-consulting/projects#11]
Please check if it satisfies the following requirements: 
< describe your free consulting project requirements briefly>
 We need to convert JSON to HTML and finally create WORD/RICH TEXT and PDF documents.

< which platform you're working on -- operating system, development environment etc.> 
 We are using WINDOWS for DEVELOPMENT ,using JAVA and ECLIPSE. Solution developed using library will be deployed on AWS

**<attach input documents>**
We can'nt share documents outside due to confidentiality. Main requirement is to convert JSON to PDF and WORD

**Comment by shahzad-latif** [comment]
@ranjeetsinghr 

Thanks for getting in touch. I understand, you can't share actual data with us due to confidentiality. However, I would suggest to share a sample similar to your original format but with dummy data, so we can see how the input looks like and if you have some desired format for the PDF and Word i.e. how the output should look like, that would be very helpful for us to understand your requirement and help you out. 

Please let me know your thoughts.

**Comment by shahzad-latif** [comment]
@ranjeetsinghr 

Can you please share some sample JSON with us? Also, do you have some stylesheet along with that like XSLT etc? We'll investigate it further.
