### ISSUE TITLE
I want to find a reliable tool to transfer PDF to XHTML

### ISSUE THREAD

**Issue by xjkxjk007** [aspose-free-consulting/projects#115]
Hello, 
I am looking for a tool to transfer the PDF document to XHTML. I found tool PDF-HTML on your site, it seems to work. But on the same site, the HTML I just got can not be transferred to XHTML. I am attaching the original PDF..
Can you recommend me a solution? (Does not need to be free, of course, I am looking for reliability and perhaps batch entry in a future).
Thanks,
Jaromir
[VZ-CORE-CAPITAL-2019.pdf](https://github.com/aspose-free-consulting/projects/files/6014940/VZ-CORE-CAPITAL-2019.pdf)

**Comment by shahzad-latif** [comment]
@xjkxjk007 

Are you talking about our [PDF to HTML Conversion app](https://products.aspose.app/pdf/conversion/pdf-to-html), or you're using our [PDF file format API](https://products.aspose.com/pdf/)?

**Comment by asadalikhan90** [comment]
@xjkxjk007 

We would like to share with you that Aspose.PDF supports PDF to XHTML Conversion feature. We have tested the scenario using the below code snippet and Aspose.PDF for .NET 21.2. We noticed that the output HTML was not in correct format:

```
var doc = new Document(dataDir + "VZ-CORE-CAPITAL-2019.pdf");
HtmlSaveOptions saveOptions = new HtmlSaveOptions();
// Make Xhtml
saveOptions.DocumentType = HtmlDocumentType.Xhtml;
// Subset only first 10 pages
//saveOptions.ExplicitListOfSavedPages = new[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
saveOptions.PartsEmbeddingMode = HtmlSaveOptions.PartsEmbeddingModes.EmbedAllIntoHtml;
saveOptions.RasterImagesSavingMode = HtmlSaveOptions.RasterImagesSavingModes.AsEmbeddedPartsOfPngPageBackground;
doc.Save(dataDir + "VZ-CORE-CAPITAL-2019.xhtml", saveOptions);
```

Therefore, an issue as **PDFNET-49474** has been logged in our issue tracking system for the sake of correction. We will further check it in details and inform you as soon as it is resolved. Furthermore, please try to create a post in our [Support Forum](https://forum.aspose.com/c/pdf) so that the ticket can be properly associated with your inquiry and you can track its progress properly.

We apologize for your inconvenience.
