### ISSUE TITLE
I want to integrate Aspose with Java and have interface which allows user to Edit PDF (similar to PDF Editor available in Aspose)

### ISSUE THREAD

**Issue by sharsh0702** [aspose-free-consulting/projects#117]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by shahzad-latif** [comment]
@sharsh0702 

We're looking into your requirements and will get back with detailed information and help.

**Comment by asadalikhan90** [comment]
@sharsh0702 

[Aspose.PDF Editor](https://docs.aspose.com/pdf/net/aspose-pdf-editor/) was just a demonstration of how API features can be used in the application code-behind to implement rendering functionality. Please note that it was not a service or product offered by Aspose and it has been discontinued. 

Furthermore, it used to [convert PDF Pages into Images](https://docs.aspose.com/pdf/java/convert-pdf-page-to-image/) and display those images into a frame/canvas over client-side. You can use the conversion feature of Aspose.PDF for Java in order to implement similar functionality. Furthermore, we have different [demo applications](https://github.com/aspose-pdf/Aspose.PDF-for-.NET/tree/master/Demos) which use Aspose.PDF for .NET in the code behind to implement different features. They are available on GitHub and you can get an idea from them on how you can implement your required functionality using Java.
