### ISSUE TITLE
ASPOSE PDF issue

### ISSUE THREAD

**Issue by dsshivak** [aspose-free-consulting/projects#132]
We use AsPOSE.PDF for .NET in our website.  I have been noticing issue with the integration.  The PDF renders but the alignment of the fields in the PDF appears messed up.  
![PDF for Aspose](https://user-images.githubusercontent.com/70489226/117180513-417dc200-ada2-11eb-80bf-383daa541a5d.PNG)

Could this be happening because of changes in the ASPOSE.PDF library?

**Comment by shahzad-latif** [comment]
@dsshivak 

Please post such bug in our [free support forums](forum.aspose.com/c/pdf/) so that we can provide timely help and can track and follow up issues properly. Please share your input/output files along with the code you're using in the above mentioned forum and our team will help you accordingly.
