### ISSUE TITLE
We want to create pdf and pptx from htmls that contain svg, and pngs (not external files).  

### ISSUE THREAD

**Issue by dbInnermedia** [aspose-free-consulting/projects#154]
Environment:  Ms Visual studio development, C#, we've purchased the Aspose Html and pdf modules. (hopefully this was all that was needed). 
We create htmls that contain svg statements and embedded png images.  the pngs can be nested inside that svg.  we currently have an wpf application with an embedded browser window.  We'll call aspose .net apis.  We purchased the .net html and pdf modules from Aspose.  
We need to create:
1. Pdfs from html that contains svg,pngs and pngs nested within svg. 
2. These have option of being printed as 2 up pages.  headers and footers alternate being aligned left or right depending on the page being left or right in 2up.  headers contain a company name and date. Footers contain page number. 
2. These need converted to powerpoint, such that the svgs convert to shapes and can be modified in powerpoint.  these can't be images (pngs can be images).  
3The zipfile contains the input html files.  Also contains an example of a pdf that would need to be converted to pptx.  and then a final example, close to what we need for an output pptx.  I attempted the basic convesions, but wasn't gettign a useful results. Either blank pdf, missing images, and in pptx,  all were slides where just images and not interactive with or shapes. thanks,
 
[TestFiles.zip](https://github.com/aspose-free-consulting/projects/files/7156107/TestFiles.zip)

**Comment by asadalikhan90** [comment]
@dbInnermedia 

We used the below code snippet to test the scenario in our environment using Aspose.HTML for .NET 21.9. 

```
string file = dataDir + "PlacematAcc.html";
Aspose.Html.Saving.PdfSaveOptions options = new Html.Saving.PdfSaveOptions();
options.PageSetup.AdjustToWidestPage = true;
using (var document = new Aspose.Html.HTMLDocument(file))
{
 Aspose.Html.Converters.Converter.ConvertHTML(document, options, dataDir + "PlacematAcc.pdf");
}
```

We were able to notice the issue in output PDF(s). Therefore, we have logged a ticket as **HTMLNET-3363** in our issue tracking system to further investigate this issue. We will surely look into its details and keep you posted with the status of its correction. Please be patient and spare us some time.

Regarding PDF to PPTX, you have shared two different PDF and PPTX files as your expected outputs. We could not test the scenario properly because PDFs were not created successfully from your HTML files in the first place. Can you please share the expected PPTX output for the same PDF that you already have shared? Also, please share the code snippet as well that you are using to perform PDF to PPTX conversion. We will further test it and address the issue accordingly.

We apologize for the inconvenience.

_PS: Please note that [Aspose Official Free Support Forum](https://forum.aspose.com/) is the right place to post such issues as you can properly track the issue resolution progress there. You can please create an inquiry in the respective forum category as well so that the issues can be logged and addressed accordingly._
