### ISSUE TITLE
Aspose.Words.Drawing.Charts

### ISSUE THREAD

**Issue by hy31337** [aspose-free-consulting/projects#17]
Insert Chart in word，How to add colors to pie charts。

**Comment by shahzad-latif** [comment]
@hy31337 

Thanks for your request. We'll get back to you with the details shortly.

**Comment by shahzad-latif** [comment]
@hy31337 

The charts can be created using default colors for now: https://docs.aspose.com/display/wordsnet/Working+with+Charts#WorkingwithCharts-CreatingOOXMLChartsfromScratchusingAspose.Words

However, specifying a color of choice is currently not supported. We'll investigate if this can be supported or not.

**Comment by hy31337** [comment]
Thank you very much. If it comes true later, please let me know

**Comment by shahzad-latif** [comment]
@hy31337 

This is to update you as currently supporting custom colors for the charts are not in the short term plan. However, in order to make sure that you get an update when this feature is support in the future, please create a new feature request in Aspose.Words forum: https://forum.aspose.com/c/words

You'll get an update on your registered email. I'm going to close this issue now. Thanks.
