### ISSUE TITLE
Regarding ASPOSE Product License and Watermark Issue

### ISSUE THREAD

**Issue by saif33757-Mohammad** [aspose-free-consulting/projects#180]
**Project brief requirement:**

“This is Mohammad Saif here working for Danske Bank. I have some queries regarding Aspose product license for our business work and I have tried connecting with the Aspose technical team through their website but I haven’t received any response yet.

**Below is my detailed query for our business work:-**

I am facing the issue regarding the Aspose. As I am working on to convert the HTML file to PDF file there I am able to convert the file easily with Aspose but the problem is I am also getting the auto generated Evaluation watermark in the PDF file.

I went into the documentation of Aspose and figured out that by setting the Aspose Product license we can get rid of the watermark. So I tried setting up the product license Aspose.PDF for .Net but still the watermark exist into the PDF file.

Can you please provide me the technical support on the product license and how we can get rid of the watermark in the PDF file.

**A Question:**
And also my question is, whenever we are consuming Aspose Products for .Net do we need to have different product licenses for each of the Aspose.PDF, Aspose.HTML, Aspose.Words, etc. respectively OR a single product license for all of the above packages will be enough?

**Device and Software details:-**
OS - Windows10.
Development Environment - .Net core, IDE- Visual studio 2019

Attaching the generated PDF file with the help of Aspose product license but the PDF contains auto generated Evaluation watermark.
[OutputSamplePDFDoc.pdf](https://github.com/aspose-free-consulting/projects/files/8132678/OutputSamplePDFDoc.pdf)

Kindly have a look on my above query and please provide me with the contact information of the Technical Support Team of ASPOSE so that we can have a direct connect with them.

Please feel free to ask any further information you may require to help us.

Best regards,
Mohammad Saif
IT Software Engineer

Danske Bank
Welcoming & Orcherstration 
Digital Signing Journey
+91 9036130820

Email: msai.danskeit.co.in , saif33757@gmail.com

**Comment by asadalikhan90** [comment]
@saif33757-Mohammad 

While working with the Aspose.PDF, please make sure that you set the license at the start of the application so that during its runtime, the API does not face any trial version limitations. Furthermore, yes, you need to set a license for all Aspose APIs separately in your code if you are using more than one APIs. There is a single license that can be obtained while purchasing Aspose.Total Package but still you would be setting it for each API like the following:

```cs
Aspose.Words.License wlicense = new Aspose.Words.License();
wlicense.SetLicense("Aspose.Total.NET.lic");

Aspose.Slides.License slicense = new Slides.License();
slicense.SetLicense("Aspose.Total.NET.lic");

Aspose.Cells.License clicense = new Aspose.Cells.License();
clicense.SetLicense("Aspose.Total.NET.lic");
```

Please try to set the license for every API at the start of your application. In case you still notice any issue, please create a post in our [dedicated support forum](https://forum.aspose.com/c/pdf) which is the right and always recommended place to post such inquiries. We will be assisting you accordingly there.

**Comment by asadalikhan90** [comment]
@saif33757-Mohammad 

> After generating PDF file I am getting "some evaluation text lines along with watermark". It will get removed when we setup the license right ?

Yes, your understanding is correct.

> While using Aspose.Words, the generated Pdf is having formatting and styling issues.
Is there any limitations with Aspose regarding css, fonts styling etc. What could be the reason, how we can resolve it ?

We are checking it and will get back to you on it shortly.

**Comment by saif33757-Mohammad** [comment]
@asadalikhan90 

I have tried using Aspose.HTML now watermark is not there but Evaluation text is still exist in the generated PDF and also yes still some formatting and font styling issue persist.

There is also one more issue is coming is that when I am trying to open my generated pdf directly from Adobe Acrobat and also the evaluation text line is getting removed. This is happening when we are downloading the file from our portal and opening in Acrobat.

I am attaching the screenshot of error, the generated pdf file and the code which I have used for pdf generation.
![IssueImage](https://user-images.githubusercontent.com/100357944/157597444-60ae9259-19d3-4e6e-9eae-0c1cc39c639a.png)

[Content (4).pdf](https://github.com/aspose-free-consulting/projects/files/8220703/Content.4.pdf)

**Code below:-**
private Task<byte[]> GenerateHtmlToPdfAsync(string html)
        {
            byte[] pdfContent = null;
            //var htmlByteArray = Encoding.UTF8.GetBytes(html);
            //HtmlLoadOptions loadOptions = new HtmlLoadOptions()
            //{
            //    IsEmbedFonts = false
            //};

            using (MemoryStream memoryStream = new MemoryStream())
            {
                var options = new PdfRenderingOptions();
                using (PdfDevice pdfDevice = new PdfDevice(options, memoryStream))
                {
                    using (var renderer = new HtmlRenderer())
                    {
                        using (HTMLDocument htmlDocument = new HTMLDocument(html, ""))
                        {
                            renderer.Render(pdfDevice, htmlDocument);
                            //Save memoryStream into output pdf file
                            pdfContent = memoryStream.ToArray();
                        }
                    }
                }
            }
            return Task.FromResult(pdfContent);
        }



**Also one request, can we have a license for the testing purpose first instead of purchasing it ? Because if we purchase it and then if license doesn't help us out or if there some other problem then purchasing would cost us terribly. 
Hope you understand us.**

**Comment by asadalikhan90** [comment]
@saif33757-Mohammad 

> I have tried using Aspose.HTML now watermark is not there but Evaluation text is still exist in the generated PDF and also yes still some formatting and font styling issue persist.

> There is also one more issue is coming is that when I am trying to open my generated pdf directly from Adobe Acrobat and also the evaluation text line is getting removed. This is happening when we are downloading the file from our portal and opening in Acrobat.

We need a sample HTML file in .zip format in order to test this scenario in our environment and address it accordingly. Can you please provide it?

> Also one request, can we have a license for the testing purpose first instead of purchasing it ? Because if we purchase it and then if license doesn't help us out or if there some other problem then purchasing would cost us terribly.
Hope you understand us.

Sure, you can apply for a [30-days free temporary license](https://purchase.aspose.com/temporary-license) with which you will be able to use the API without any trial version limitations. Furthermore, we again request you create a post in our [dedicated support forum](https://forum.aspose.com/c/html/29) as it is the right place to discuss such issues.

**Comment by AlexNosk** [comment]
@saif33757-Mohammad
> While using Aspose.Words, the generated Pdf is having formatting and styling issues.
Is there any limitations with Aspose regarding css, fonts styling etc. What could be the reason, how we can resolve it ?

Could you pleases zip and attach your input HTML document here for testing? We will check the issue and provide you more information.

**Comment by saif33757-Mohammad** [comment]
@asadalikhan90 , @AlexNosk :

Hi,

Thanks for the responses! :)

Please find the attached HTML files in .zip along with the actual/resultant PDF document named as "Content.pdf" for your reference which we want to be generated using Aspose.HTML API from HTML to PDF.
[SignaturesListHTMLFiles.zip](https://github.com/aspose-free-consulting/projects/files/8243870/SignaturesListHTMLFiles.zip)
[Content.pdf](https://github.com/aspose-free-consulting/projects/files/8243876/Content.pdf)

Please have a look.

Regards,
Saif

**Comment by asadalikhan90** [comment]
@saif33757-Mohammad 

Regretfully, we cannot test the scenario using these partial HTML files i.e. .cshtml. Can you please share full HTML form of document which we can also render in browser to see actual results? Also, we opened the PDF document that you shared i.e. Content.pdf and we did not notice any error message by Adobe Reader while viewing it. It is also possible that you are facing this error due to absence of required fonts. 

Please try to open this PDF on another system where all required fonts are installed. In case issue still persists, please share the sample HTML files as requested above and we will further proceed to assist you accordingly.

**Comment by saif33757-Mohammad** [comment]
@asadalikhan90 

The above mentioned Content.pdf is the original one, you can use that one as a reference. We want to create same pdf with the help of Aspose.

Now I am facing CSS issue in the footer part of generated pdf. Please compare my attached file which I have generated from Aspose.HTML with the original one mentioned in the above comment named as Content.pdf or else I am again attaching it in this comment.

Please have a look and tell me how I can solve the CSS issue in the Aspose. Is there any specific CSS required for Aspose document generation or general CSS will work for any Aspose document generation?

Original document:
[Content.pdf](https://github.com/aspose-free-consulting/projects/files/8251474/Content.pdf)

Aspose.HTML generated pdf document:
[Content (5)-pages-2.pdf](https://github.com/aspose-free-consulting/projects/files/8251476/Content.5.-pages-2.pdf)

**Comment by asadalikhan90** [comment]
@saif33757-Mohammad 

There is no specific type of CSS required during generation process by Aspose.HTML. However, we did check your documents and noticed that one of them is created by Aspose.PDF instead of Aspose.HTML. Furthermore, as requested earlier, we do need sample HTML files which can be rendered in browser so that we can try to convert them in our environment and observe the issue. This way we will be able to address it accordingly.

**Comment by saif33757-Mohammad** [comment]
Which one has been converted with Aspose.PDF ?

The document Content(5)-pages-2.pdf is converted with Aspose.HTML for sure. 

And regarding the HTML files, those files I cannot because of restriction by my organization.

**Comment by asadalikhan90** [comment]
@saif33757-Mohammad 

The file "Content.pdf" shows Aspose.PDF for .NET 21.4 in its properties as creator/producer. Nevertheless, we are afraid that we cannot address the issue related to CSS without replicating it in our environment. You can create a sample HTML document with CSS reference which you can share and which can be used to reproduce the issue. This would help us in addressing the issue accordingly.
