### ISSUE TITLE
The slide show settings for the presentation are changed while converting PPT to PPTX.

### ISSUE THREAD

**Issue by MiniCassie** [aspose-free-consulting/projects#184]
The slide show settings for the presentation are changed while converting PPT to PPTX,such as ShowType、LoopUntilStopped、ShowWithNarration、ShowWithAnimation、StartingSlide、EndingSlide.
[Test3.zip](https://github.com/aspose-free-consulting/projects/files/8160350/Test3.zip)
![image](https://user-images.githubusercontent.com/49870259/156141121-75f112c1-1b7e-4dc9-8c9c-440ad4869ce4.png)
![image](https://user-images.githubusercontent.com/49870259/156141481-4c148191-fa64-4edd-b9e0-3de1756c2867.png)

**Comment by andreypotapovaspose** [comment]
@MiniCassie,
Thank you for reporting the issue.

I've reproduced the problem with changing Slide Show settings and added a ticket with ID **SLIDESNET-43095** to our issue tracking system. We apologize for any inconvenience. Our development team will investigate this case. You will be notified when the issue is resolved.
