### ISSUE TITLE
Questions about Pdf Limitation and Load

### ISSUE THREAD

**Issue by Prasanna8405** [aspose-free-consulting/projects#185]
We are thinking to use Aspose Pdf component to handle the pdf conversion in our application. But we are still unclear about the Limitation of Pdf generation and the Load handling.

How much Load will it support to do the pdf conversion? (e.g. in a sequence if we send 100 request at a time to do the pdf conversion will it work without any crash?)

What is the limitation of handling the pdf conversion? (e.g. if i send a document size around 800MB -1024MB will it be able to handle it for doing the Pdf conversion?)

**Comment by asadalikhan90** [comment]
@Prasanna8405 

There is no such limitation in the API regarding PDF Size or the number of PDFs you want to process at a time. You can process as many files as you want. However, please note that Aspose.PDF is a multithreaded safe API which means one thread should access one PDF document at a time. In other words, one PDF document should be processed and accessed by one single thread at one time in order to prevent any type of issue. 

Also, please clarify if you are interested in On-Premise API or Cloud API so that we can provide feedback accordingly. Please also note that [Aspose.PDF Official Support forum](https://forum.aspose.com/c/pdf) is the right and recommended place to post such inquiries. Please try to create a post there and will assist you accordingly.
