### ISSUE TITLE
I want to create/build a page using asp.net core to read/extract mail message header 

### ISSUE THREAD

**Issue by abigailkaku** [aspose-free-consulting/projects#19]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by shahzad-latif** [comment]
@abigailkaku 

Thanks for your interest in free consulting service. We'll provide you a solution soon.

**Comment by abigailkaku** [comment]
Thank you so much

**Comment by shahzad-latif** [comment]
@abigailkaku 

Please check the following project built using Aspose.Email for .NET and ASP.NET Core: https://github.com/aspose-free-consulting/create-page-using-asp.net-core-to-read-email-message-header

I hope this will be a good start for you to explore more features of Aspose.Email API and take your project to the next level. 

If you find any further questions, please do let us know.

**Comment by abigailkaku** [comment]
@shahzad-latif  

Thanks! 
But sorry what I mean is like message header analysis.

**Comment by shahzad-latif** [comment]
@abigailkaku 

Can you please elaborate what you mean by "message header analysis"?

**Comment by abigailkaku** [comment]
@shahzad-latif 

It's like I get the message header from my email and I have a page can convert(read) it.
Like a report.
![exrca-header-analyzer-report-600x358](https://user-images.githubusercontent.com/50519986/68734104-07e85280-0614-11ea-9c3e-236e88e27d66.jpg)

**Comment by abigailkaku** [comment]
@shahzad-latif 

Just don't know what method I need to use to convert the message header.
And I saw the examples from Aspose, know the GetDecodedValue may the method I need. Still confused now...
Or could you please tell me the step (simple way is fine), like which method I should use in controller.
Sorry and really thanks.

**Comment by shahzad-latif** [comment]
@abigailkaku 

Thanks for sharing further update. We'll get back to you soon with details.

**Comment by abigailkaku** [comment]
@shahzad-latif Thanks for your help

**Comment by mudassirfayyaz** [comment]
@abigailkaku ,

We have observed the requirement image shared by you. Actually, you are trying to extract the receive header information form message. Till this level, Aspose.Email API does support extracting the receiver header information and represent that in a Receive Header key with a string.

I have worked on one of examples and it has following extracted Received header information:

**sys190.ZenQaTest1.com with Microsoft SMTPSVC(6.0.3790.3959);	 Thu, 1 Apr 2010 11:09:33 +0530,from [192.168.2.39] ([192.168.2.39]) by Ex2003Test1.ZenQaTest1.com with Microsoft SMTPSVC(6.0.3790.3959);	 Thu, 1 Apr 2010 11:09:30 +0530**

So, as per your requirement image of received header, you probably want to extract following information from above header in following form:

submitting host: Ex2003Test1.ZenQaTest1.com
receiving host: sys190.ZenQaTest1.com
time :  Thu, 1 Apr 2010 11:09:33 +0530
type: Microsoft SMTPSVC(6.0.3790.3959)
delay:  Thu, 1 Apr 2010 11:09:33 +0530 time - Thu, 1 Apr 2010 11:09:30 +0530

The API extracts the complete header and in order to represent the different portions of header information as mentioned in your required image, one has to write his own string parsing application to parse and extract the header data as per your requirement. However, the issue that the header information is not constant and it will either have some or all information sub-strings available in overall header string. Secondly, there can be multiple iterations of data received header information as well.

The API does not have such support as it fetches the complete header information. The header information continue to append further when message hopes from one to other server or between different clients. So we cannot devise a generalized string tokenizer for this. However, if you still want to extract and represent the information, you may share your message file with us and we can try to write parser to meet your requirements and display the content as you like to have. But the implemented scheme may or may not be applicable to another email MSG. I hope this will clarify the limitations and possible choices to you.
