### ISSUE TITLE
PPT to PPTX conversion changes the format for the automatically updated date and time of headerfooter

### ISSUE THREAD

**Issue by MiniCassie** [aspose-free-consulting/projects#201]
PPT to PPTX conversion changes the format for the automatically updated date and time of headerfooter
**Code：**
string src = "C:\test.ppt";
string dst = "C:\test.pptx";
Aspose.Slides.Presentation presentation = new Aspose.Slides.Presentation(src);
presentation.Save(dst, Aspose.Slides.Export.SaveFormat.Pptx);
[test.zip](https://github.com/aspose-free-consulting/projects/files/8569925/test.zip)
![image](https://user-images.githubusercontent.com/49870259/165466636-fa399d82-595f-4886-bb95-ddca2632b441.png)
![image (1)](https://user-images.githubusercontent.com/49870259/165466638-78f55a27-f200-4fd0-bbe8-de1322461090.png)
![image (2)](https://user-images.githubusercontent.com/49870259/165466646-8a794b06-3a66-4e84-9d75-a644197db871.png)

**Comment by andreypotapovaspose** [comment]
The issues you have found earlier (filed as SLIDESNET-43183) have been fixed in Aspose.Slides for .NET 22.11 (<a href="https://releases.aspose.com/slides/net/new-releases/aspose.slides-for-.net-22.11dlls-only/">ZIP</a>, <a href="https://releases.aspose.com/slides/net/new-releases/aspose.slides-for-.net-22.11/">MSI</a>).
You can check all fixes on the <a href="https://docs.aspose.com/slides/net/aspose-slides-for-net-22-11-release-notes/">Release Notes</a> page.
You can also find the latest version of our library on the <a href="https://releases.aspose.com/slides/net/">Product Download</a> page.
