### ISSUE TITLE
I want to generate documents for my SharePoint/SPFx projects

### ISSUE THREAD

**Issue by MaciejEgermeierFrontex** [aspose-free-consulting/projects#209]
**< describe your free consulting project requirements briefly>**
We need to generate word/pdf documents for our custom SharePoint 2019 apps that are using SPFx.
**< which platform you're working on -- operating system, development environment etc.>** 
We are developing couple of custom modules in onPrem SharePoint 2019 using SharePoint custom apps build on SPFx. As a supporting mechanism we are using additional WCF service to "process things" requested from SPFx web app. This WCF service is .NET code web service.
I think good idea would be to have a specific WCF service to transform files based on the request from the module and get generated document in response that would be saved in SharePoint list. In this scenario we will probably need Aspose.Words for .NET
As alternative maybe we could initiate SharePoint workflow for each transformed document. In this case each module would initiate specific workflow in some specific site collection using Aspose.Words for SharePoint. Then consume the outcome of the workflow.
**attach input documents**
Source data for the documents is usually sharepoint lists. We need to put data from those sharepoint lists in document "placeholders" to generate like in mail merge.
**attach any sample required output documents if you have** 
Those documents are usually some kind of agreements.

Major question is about **licensing scheme** we should use.
- SharePoint 2019 app run on one SharePoint farm
- WCF service is just a virtual machine with IIS and multiple SharePoint modules can possibly use it.
- Developers from different vendors work on specific modules. It is hard to manage which developers would develop the product. But maybe we could limit the number of devs if only one will develop WCF service or SharePoint workflow for document generation.
- Multiple modules need to generate those files using Aspose.
- The modules are used both internally and by external parties. So it is hard to say what are the physical locations.
- Can we switch to which developer the license is assigned to when we change the responsibility for this functionality to other dev?

Thanks in advance for help.

**Comment by haleystuart** [comment]
Hello MaciejEgermeierFrontex,

The Aspose licenses for SharePoint are defined at this link: https://purchase.aspose.com/policies/exporters-license-types 

As you review the license types you can see that it depends on the type of license purchased on what it will allow the customer to do. Please review the license types, and let us know if you have additional questions.

Thank you, 
Aspose Team

**Comment by MaciejEgermeierFrontex** [comment]
Hello Aspose Team,
I’ve reviewed your licensing. At page https://purchase.aspose.com/policies/use-within-public-sdk-or-api you mention public API. How do you define public API?
In my case I think I need WCF service that would be used by different SharePoint sites/modules. Do you consider this as public API and metered license is required?

**Comment by haleystuart** [comment]
Hello MaciejEgermeierFrontex,
Licenses for SharePoint, Reporting Services and JasperReports are based on the number of developers and the number of servers that the components will be deployed to. (Each server can be located at one physical location, for example one of your organization's offices.)

We have two sizes of developer licenses: single or up to ten developers.
We offer three sizes of server licenses: single, up to 10 servers and unlimited.

The .NET and Java licenses are concerned with the number of developers and the number of locations to which any end user software (products created with the APIs) are used in. A location can be an office, for example, or any building with its own postal address.

The Android licenses work a little differently. They look to how many apps are created, as well as how many places they are deployed to. There are two options for the latter: Enterprise deployment (for use in one company only) or OEM (unlimited deployment to unlimited companies). An OEM license is used if you are selling the app on a marketplace. A Developer license lets you develop one app and a Site license lets you create up to ten.

The Exporter licenses (SharePoint, Reporting Services, JasperReports) work differently as well, once a SharePoint component is installed, for example, it's features are available to all users of that SharePoint site. So instead of looking at physical locations, the license limits the number of physical servers that the component can be used on.

**Comment by MaciejEgermeierFrontex** [comment]
Could you provide formal license document for your product?

**Comment by haleystuart** [comment]
Hello MaciejEgermeierFrontex,

The Aspose EULA can be found here: https://about.aspose.com/legal/eula/ 
If you have any other questions, please let me know.

Thank you,
Aspose Sales Team
