### ISSUE TITLE
I want to create/build 

### ISSUE THREAD

**Issue by kumaresan65** [aspose-free-consulting/projects#214]
Hi Team,
Following is my requirement. Please let me know what kind of product and license type i can purchase.

Requirement:
Need to merge all Word, pdf, excel, notepad, email documents into single pdf using Aspose.Total
I will develop this as executable DotNet background application and host it using windows task scheduler in my production server.

It will be running as single instance in UAT server for testing and later in production server. 
Please let me know what kind of license type i can go for

**Comment by asadalikhan90** [comment]
@kumaresan65 

You can use conversion and merge features of [Aspose.PDF](https://docs.aspose.com/pdf/net/merge-pdf-documents/), [Aspose.Cells](https://docs.aspose.com/cells/net/combine-multiple-workbooks-into-a-single-workbook/), and [Aspose.Words](https://products.aspose.com/words/net/merge/docx/) in order to accomplish what you require. However, please note that we have dedicated forum for such inquiries and discussions. Please post you inquiry in our [dedicated support forum](https://forum.aspose.com/c/total) where we will provide further technical details. Also, your license/sales related inquiries can be entertained by contacting our [Sales Team](https://forum.aspose.com/c/purchase).
