### ISSUE TITLE
I want to implement the interface(com.apose.slides.Collections.ICollection), but failed to rewrite the copyTo method because there is conflict between java int and apose int

### ISSUE THREAD

**Issue by jxy604803280** [aspose-free-consulting/projects#218]
I want to implement the interface(com.apose.slides.Collections.ICollection), but failed to rewrite the copyTo method because there is conflict between java int and apose int, just show like the pic
![image](https://user-images.githubusercontent.com/7273362/174462369-a08a9d54-74ee-42f0-b737-e684b46f6d67.png)

**Comment by andreypotapovaspose** [comment]
@jxy604803280,
I've added a ticket with ID **SLIDESJAVA-38832** to our issue tracking system. Our development team will investigate the case. We will reply to you soon.

**Comment by andreypotapovaspose** [comment]
@jxy604803280,
Our developers have investigated the case.

> conflict between java int and apose int

We added these classes to API due to compatibility reasons. We do not have plans to provide full access to all collection classes and interfaces. Could you please clarify, why you want to use `com.aspose.slides.Collections.ICollection` interface?
