### ISSUE TITLE
Not able to add local link by specifying the target text. (Found example only for target page number)

### ISSUE THREAD

**Issue by E6AM** [aspose-free-consulting/projects#222]
Hello Team,

We Want to add local hyperling from one texxtfragment to other based on the content. We don't know the pagenumber of the target textfragment. we know only target text content.
Post processing textfragmentAbsorve method works but not suits for big documents.
Please let us know any features to add local hyperlink by specifying target text.
And how to use "LocalHyperLink.Target" in aspose. I found example only on LocalHyperLink.TargetPageNumber

Thanks,

**Comment by asadalikhan90** [comment]
@E6AM 

> We Want to add local hyperling from one texxtfragment to other based on the content. We don't know the pagenumber of the target textfragment. we know only target text content.
Post processing textfragmentAbsorve method works but not suits for big documents.
Please let us know any features to add local hyperlink by specifying target text.

At the moment, API only offers this way to add local hyperlinks to a text fragment. As per your case, you have to use TextFragmentAbsorber in order to find the target TextFragment in the PDF because PageNumber is unknow. However, if you are facing some issue while using this method, it needs to be investigated. We recommend you post your issue while creating a new topic in our dedicated support forum where you will be assisted accordingly.

* [Aspose.PDF Free Suppor Forum](https://forum.aspose.com/c/pdf)

> And how to use "LocalHyperLink.Target" in aspose. I found example only on LocalHyperLink.TargetPageNumber

You can set [LocalHyperLink.Target](https://reference.aspose.com/pdf/net/aspose.pdf/localhyperlink/target/) Property to any Class that inherits BaseParagraph like TextFragment. Furthermore, please create a new topic in our support forum as requested above as it is the right place to discuss such issues.
