### ISSUE TITLE
Know More About Aspose

### ISSUE THREAD

**Issue by nivas2k3vb** [aspose-free-consulting/projects#228]
Sir,
We are using Appian Enterprise Cloud Application. We are generating PDF documents by using  an API through Appian . Once the document is generated it will be e-Signed. We have the requirement of combining the Non e-Signed as well as  e-Signed document. We don't have any functionality in Appian to do that. I searched in Google and I got the information that Aspose will provide the PDF merging functionality. We need tools like Aspose PDF which can do this task. I need to do POC for it.

I have chosen Aspose PDF tool for POC and I need to submit my recommendation to my organization .
I kindly request you to provide the following details :

1) Whether Aspose.PDF tool supports for both Linux & Windows Platform in case if we store the Documents in both the platform and combine the PDF?
2) Aspose.PDF is licensed or Open source tool?
3) In case if Aspose.PDF is an open source tool can we deploy the community edition in cloud platform?
4) If we go for community edition will I get Support from Aspose if we face any error or issue?
5) If we go with enterprise edition I request the details of Pricing and Support details.
6)  our Appian cloud is "Platform as Service" type. I am not sure this tool can be installed in the same server or not. In this case we need separate VM cloud to install this? or Which type of cloud support you will provide for this tool?
7)  What will be the performance of Aspose.PDF tool in case to process large amount of documents?
8) In case of urgent & critical issues how we need to get the support?
9) Is it possible to call the Aspose.PDF merge tool to be called from Appian cloud by using API to merge the document?
10) If any other information you want to provide which is not raised  in my thought please provide it. 

Please kindly provide all the details so that it will be helpful to move forward.

**Comment by asadalikhan90** [comment]
@nivas2k3vb 

Thanks for showing interest in our API. We are gathering related details to share with you and will get back to you shortly.

**Comment by nivas2k3vb** [comment]
Hi @asadalikhan90 - I would appreciate  if you provide the details at the earliest . We need to take the decision based on your inputs.

**Comment by asadalikhan90** [comment]
@nivas2k3vb 

> Whether Aspose.PDF tool supports for both Linux & Windows Platform in case if we store the Documents in both the platform and combine the PDF?

Yes, Aspose.PDF for .NET supports .NET Core and can be used in both Windows and Linux environments. Furthermore, Aspose.PDF also comes in Java flavor that can also be used in both environments.

> Aspose.PDF is licensed or Open source tool?
> In case if Aspose.PDF is an open source tool can we deploy the community edition in cloud platform?
> If we go for community edition will I get Support from Aspose if we face any error or issue?

It is licensed API and you would need to buy the license with one year of subscription in order to use the API. The license is set in the code before using the API Classes and methods. Further information can be found in "[Licensing](https://docs.aspose.com/pdf/net/licensing/)" section of the API documentation. You can also apply for a [30-days free temporary license](https://purchase.aspose.com/temporary-license) to evaluate the API without any restrictions.

> If we go with enterprise edition I request the details of Pricing and Support details.
> In case of urgent & critical issues how we need to get the support?

You will always be entitled to get support for free via our dedicated [free support forums](https://forum.aspose.com/c/pdf). However, we also offer different support options (in addition to the licensing) e.g. [Paid Support](http://helpdesk.aspose.com/) which can be used to report issues that need to be resolved on urgent basis and are showstopper. Please create an inquiry in our [Purchase Forum](https://forum.aspose.com/c/purchase) where you can connect with our Sales team to get answers about your pricing related inquiries.

> our Appian cloud is "Platform as Service" type. I am not sure this tool can be installed in the same server or not. In this case we need separate VM cloud to install this? or Which type of cloud support you will provide for this tool?
> Is it possible to call the Aspose.PDF merge tool to be called from Appian cloud by using API to merge the document?

Well, in such cases, you should also check Cloud APIs offered by Aspose. [Aspose.PDF Cloud SDKs & REST APIs ](https://products.aspose.cloud/pdf/family/)are also available for PDF Generation & Conversion.

> What will be the performance of Aspose.PDF tool in case to process large amount of documents?

There is no such restrictions in the API in terms of file size. However, larger files and complex structures of the supplied documents require more memory and resources to get processed. In case of some issues, you can freely contact us in our [Free Support Forum](https://forum.aspose.com/c/pdf) and we will address the reported issue.

Lastly, we recommend posting such inquiries and questions in our dedicated support forums that is the right place for such discussions. Please try creating a topic there where you will be assisted accordingly.
