### ISSUE TITLE
Trial version; The signature problem

### ISSUE THREAD

**Issue by Git-HHHH** [aspose-free-consulting/projects#23]
The header of the converted file has a "Evaluation Only. Created with Aspose.Words. Copyright 2003-2018 Aspose Pty Ltd." signature,Doesn't the official version have this problem?

**Comment by shahzad-latif** [comment]
@Git-HHHH 

This is because you're using an evaluation version. The licensed versions doesn't have this message. If you want to evaluate before you buy, without any limitations, then please get a temporary license and try out the features: https://purchase.aspose.com/temporary-license

Also, please use our forums for quick support regarding this and other issues: https://forum.aspose.com/ as this space is reserved for consulting projects only. Thanks for your understanding.
