### ISSUE TITLE
when will "WORDSNET-12704" goes to live?

### ISSUE THREAD

**Issue by vs6060cn** [aspose-free-consulting/projects#24]
hi,

we need the below feature,WORDSNET-12704
(by the task ,i can set the activex value (for example active x forms.combobox.1 properties)

thank you very much

**Comment by shahzad-latif** [comment]
@vs6060cn 

This issue is still in development and I'm afraid, right now, we do not have any ETA for the resolution. Please note that this place is just to handle any free consulting projects. So I would encourage you to follow up any issues or ask other related questions in our forums in the relevant thread or create a new thread. https://forum.aspose.com/ 

I would really appreciate your cooperation. Thank you.
