### ISSUE TITLE
Aspose.PDF for .NET Infrastructure suggestions

### ISSUE THREAD

**Issue by E6AM** [aspose-free-consulting/projects#256]
We are saving the pdf Document object to a stream, We are facing a performance issue with ASPOSE Pdf, It’s taking 4-5 mins for the document with the below properties. Please suggest the infrastructure needs to improve the performance.
Document with 1000 pages and size around 2-3MB after compression[before compression 10-11MB].

**Comment by asadalikhan90** [comment]
@E6AM 

The issue seems related to specific document structure and it needs proper investigation. We request you please create a new topic in [Aspose.PDF official support forum](https://forum.aspose.com/c/pdf/10) along with sharing sample code snippet and sample PDF file. We will further proceed to assist you accordingly.
