### ISSUE TITLE
When i generate a resultant file by comparing 2 HTML file, using ASPOSE words library, I would like to update formatting (color, strikethrough, font, etc) for removed and added text. How can i achieve that?

### ISSUE THREAD

**Issue by cg17troon** [aspose-free-consulting/projects#287]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by AlexNosk** [comment]
@cg17troon If you render your output document (convert document to fixed page formats like PDF, XPS, Image etc), you can control appearance of revisions using properties of [RevisionOptions](https://reference.aspose.com/words/net/aspose.words.layout/revisionoptions/) class.
In case of saving the document to MS Word formats, there is no way to control appearance of revisions, since these setting are set in the consumer application and are not stored in the document.
