### ISSUE TITLE
Image is not getting printed properly while converting HTML to Image using Java 

### ISSUE THREAD

**Issue by SBandyopadhyay2021** [aspose-free-consulting/projects#315]
I am trying the convert HTML to Image but it is observed that Image is not getting printed. I have used Java code.
If the HTML contain table with 1 row and 1 column and that contain 3 images, in that case after converting to Image, all the 3 images are not coming in the same row.
I am attaching the HTML file for your reference.

I have used aspose-words-23.5-jdk17.jar

I am not able to add the problematic HTML file.

**Comment by AlexNosk** [comment]
@SBandyopadhyay2021  It is difficult to say what the problem is without actual document. Please note, the main place or getting support is Aspose.Words support forum. So please post your questions and attach problematic document in the forum to get timely response:
https://forum.aspose.com/c/words/8
