### ISSUE TITLE
你好 我想要导出layerGroup 中包含效果，导出不含效果？

### ISSUE THREAD

**Issue by kkgg0521** [aspose-free-consulting/projects#320]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by kkgg0521** [comment]
![_1JB1D0E9U`WH 0(_J%T@B5](https://github.com/aspose-free-consulting/projects/assets/59002786/c65658b7-6c2a-4d5f-b873-d2d12d2c1e20)

**Comment by dimsa** [comment]
@kkgg0521 could you please provide the input file for testing and the code you try to use. The answer depends of the installed fonts on your machine. In any case, it's better to use https://reference.aspose.com/psd/net/aspose.psd.fileformats.psd.layers.text/itextportion/ API because it gives the ability to use diffrent styles and paragphas in the one Text Layer.

Automatic translate: 您能否提供用于测试的输入文件以及您尝试使用的代码。答案取决于您机器上安装的字体。无论如何，最好使用 https://reference.aspose.com/psd/net/aspose.psd.fileformats.psd.layers.text/itextportion/ API，因为它能够在一个文本层。
