### ISSUE TITLE
converting .imed file to .stl or .obj file

### ISSUE THREAD

**Issue by elfekyarno** [aspose-free-consulting/projects#331]
I am not able to convert .imed file to .stl or .obj file as it gives me file is unsupported.

**Comment by asadalikhan90** [comment]
@elfekyarno 

We need your sample file along with the sample code snippet to investigate the case and check its feasibility in our environment. Can you please create a post in our [official support forum](https://forum.aspose.com/c/3d) along with the requested information so that we can test the scenario in our environment and address it accordingly. Also, please note that Aspose Forums are the right and the recommended place to discuss such issues.
