### ISSUE TITLE
i got a checkbox symbol not converted in the pdf file 

### ISSUE THREAD

**Issue by andrew97s** [aspose-free-consulting/projects#376]
hi

i use the aspose to convert a word file into a pdf file ,
recently i found a checkbox symbol not converted in the pdf file ,
and i checked it's a simsun font ,and my system does install the font.

below as the original word file and  converted pdf file screenshot:

[pdfconvert.docx](https://github.com/aspose-free-consulting/projects/files/13964551/pdfconvert.docx)

![image](https://github.com/aspose-free-consulting/projects/assets/66058819/20ac0f32-8658-485c-88c1-0986418b8eb8)

**Comment by AlexNosk** [comment]
@andrew97s The problem is not reproducible on my side. Most likely the problem occurs because the fonts required for rendering document are not available on the machine where document is converted to PDF. If Aspose.Words cannot find the font used in the document, the [font is substituted ](https://docs.aspose.com/words/net/manipulating-and-substitution-truetype-fonts/). This might lead into fonts mismatch and document layout differences due to the different fonts metrics. You can implement [IWarningCallback ](https://reference.aspose.com/words/net/aspose.words/iwarningcallback/)to get notifications when font substitution is performed.
Please see our documentation to lean where Aspose.Words looks for fonts:
[https://docs.aspose.com/words/net/specifying-truetype-fonts-location/ 1](https://docs.aspose.com/words/net/specifying-truetype-fonts-location/)

PS: The main place for getting support in our [support forum](https://forum.aspose.com/c/words/8).
