### ISSUE TITLE
I want to use the Document object after save it to an outputStream

### ISSUE THREAD

**Issue by xiaoao98** [aspose-free-consulting/projects#411]
Product: Aspose.pdf, language: Java
I save the Document to an outputStream, and I need to use the object after it is saved, then I find the object is disposed of.  I find that save function has a saveOptions parameter, but how to use it?

My code:
```
doc = new Document(filePath);
val baos = new ByteArrayOutputStream();
doc.save(baos);
//some operations of baos
val docInfo = doc.getInfo();
log.info("{} docInfo", docInfo.getCreationDate()); //this line will throw an exception that the object is disposed of
```

I try to add saveoptions parameter for save function like that, but it does not work
```
import com.aspose.pdf.SaveOptions;
public class MySaveOptions extends SaveOptions {
}
val mySaveOptions = new MySaveOptions();
mySaveOptions.setCloseResponse(false);
doc.save(baos, mySaveOptions);//will throw an null pointer exception
```
So how to solve this problem? Thank you very much!

**Comment by johnpatrickoldfield** [comment]
[Bank And or Finance Integration Tool Fictional.pdf](https://github.com/user-attachments/files/15747573/Bank.And.or.Finance.Integration.Tool.Fictional.pdf)

https://www.figma.com/board/5kEiKTpTYnpNWni7bOumj2/Bank-And-or-Finance-Integration-Tool-Fictional?node-id=8-1559&t=45oOzbqg8Qc3Vuhs-0 - the front end dashboards are allowing and or making permanent numerical updates and UI updates to the table lines? Please show me where to query if not correct comment slot by sending instructions!?

**Comment by asadalikhan90** [comment]
@xiaoao98 

After saving the Document into FileOutputStream, you need to re-initialize the document by taking byte array from output stream like below:

~~~ java
document.save(pdfOutputStream);
Document pdfDocument = new Document(pdfOutputStream.toByteArray());
~~~

Please note that the save method behaves like dispose because it closes all opened objects in memory related to the document being saved. Therefore, you need to re-initialize the document in order to keep working on it. Save options are not related to it. It is an interface that you can use to save document into different file formats.

**Comment by xiaoao98** [comment]
Got it, thank you! After I use the ByteArray to create a new document. I found the metadata Producer Info of the pdf is changed. Is there any other information that has been changed?

**Comment by asadalikhan90** [comment]
@xiaoao98 

This needs to be investigated. Can you please create a post in our [dedicated support forum](https://forum.aspose.com/c/pdf) which is the recommended and right place to have such discussions? We will further proceed to assist you accordingly.
