### ISSUE TITLE
window运行的了 Linux却报错

### ISSUE THREAD

**Issue by cyb-292** [aspose-free-consulting/projects#418]
java项目  报java.langUnsatisfiedLinkError:no fontManager in java.library.path

**Comment by amjad-sahi** [comment]
@cyb-292,
 
By checking the error trace, your issue seems out of scope or out of context for Aspose (Java) APIs. Typically, the java.lang.UnsatisfiedLinkError: no fontManager in java.library.path error occurs when the JVM cannot find a required native library that is necessary for fonts management. This issue may arise when running Java applications on Linux systems if the application relies on fonts or font-related operations but not found. Please try to install the JRE with GUI support. Also, install the fontconfig and ttf-dejavu packages. 

You should check and browse the internet to find the respective documents, blogs, or resources to sort out your issue. For example,
https://stackoverflow.com/questions/37251309/no-fontmanager-in-java-library-path
https://github.com/schemaspy/schemaspy/issues/133

In case you encounter the issue with any Aspose (Java) library/API, please specify which Aspose for Java API you are using. Please provide a test case and Java (runnable) code or app with resource files to reproduce the issue. Also, zip and attach sample source files (if any). We will investigate your issue promptly.
