### ISSUE TITLE
I want to create a console app that extract attachments from email (msg) and convert/merge into one PDF

### ISSUE THREAD

**Issue by kxlin913** [aspose-free-consulting/projects#49]
The preferred language: Powershell Script
The input: folder path to MSG files
The output: One PDF that contains email body and all attachments, one msg file after another.

Example:
c:\msgfiles\email1.msg (attachments:  word1.docx, excel1.xlsx,pdf1.pdf)
c:\msgfiles\email2.msg (attachments: pdf2,word2.docx, excel2.xlsx )

extractEmail.ps1 -path c:\msgfiles -ouput myout.pdf

In myout.pdf:
----
email1 body
word1.docx
excel1.xlsx
pdf1.pdf
email2 body
pdf2.pdf
word2.docx
excel2.xlsx

**Comment by mudassirfayyaz** [comment]
@kxlin913 .

We have worked over your requirements. You have shared that you are interested in fetching the body of message, the attachments that can be an Excel file, Word file and a PDF file in Message. I like to share that in order to meet this requirement, you need to use following APIs to fulfill 
 the requirements:

1. Aspsoe.Email to process the email MSG and extract attachments
2. Aspsoe.Cells will be used to save extracted Excel file as PDF
3. Aspose.Words will be used to save extracted word document as PDF
4. Aspose.PDF will be used to save the extracted PDF and also merging all different types of attachment PDF files to a single PDF

I have shared the sample MSG files [over this link](https://drive.google.com/file/d/13nKsigWT8nQpaJ_o35Xe0MHY6QQ7aW1u/view?usp=sharing
). The sample console based application can be found [over this link](https://drive.google.com/file/d/1FROxY18of9H-Q3hIdFKdR6wKsNxAO4jq/view?usp=sharing). Please make sure that you need to use valid Aspose.Total license to use the above mentioned APIs.

You need to provide the [command line arguments](https://i.imgur.com/pWh7tGQ.png) for:
1: Path where source MSG files will be located
2: Generated PDF name

[This image link](https://i.imgur.com/44Q8xS3.png) show the preview of the source MSG files and [this image link](https://i.imgur.com/ufvUGxd.png) show the preview of generated PDF.

I hope the shared solution will be helpful. Please share, if we may help you further in this regard.

**Comment by kxlin913** [comment]
Can the email body part look like the outlook printout, e.g. including From/To/CC/Subject and list of attachments etc.

**Comment by mudassirfayyaz** [comment]
@kxlin913 .

Please try using modified sample project for your convenience from [this link](https://drive.google.com/file/d/147sjJs7VrQ3G9wcO07bQR-eTR8fcuyfw/view?usp=sharing).

**Comment by kxlin913** [comment]
Sorry I can only run Powershell script. Can you please run the new app against the test messages and post the generated PDF?

**Comment by mudassirfayyaz** [comment]
@kxlin913 

We have added a small sample project for meeting the stated requirements on Github too. Please proceed to t[his Github link](https://github.com/aspose-free-consulting/Extracting-attachemnts-from-Email-and-Saving-as-PDF) for your convenience. I hope this will be helpful to you.
