### ISSUE TITLE
I want to create/build mobile application using xamarin form read, calculation excel file

### ISSUE THREAD

**Issue by anhtuan0030** [aspose-free-consulting/projects#5]
Dear Aspose Support,

I want to using aspose.cell with my mobile application, it was built on xamarin form framework. I check aspose cell support Xamarin iOS and Xamarin Droid but I can't found any sample or document about it. Can you share with me some information. Thanks!

link feature: https://docs.aspose.com/display/cellsnet/Feature+Overview

Regards,

**Comment by shahzad-latif** [comment]
@anhtuan0030 ,

You may use Aspose.Cells for .NET with Xamarin. When you install or unzip the Aspose.Cells for .NET package, you'll get Aspose.Cells for Android via Xamarin and Aspose.Cells for iOS via Xamarin which you can use in your project. 

Here are some differences and limitations of Xamarin DLLs: https://docs.aspose.com/display/cellsnet/Aspose.Cells+for+iOS+via+Xamarin+Limitations+and+API+Differences

Other than that the features and code samples are same as for .NET which you can use in your project. 

Moreover, please note that this space is not for queries or bug reports. This is to manage free consulting projects of our customers. So in order to get quick customer support and help, please post your queries in our forums: https://forum.aspose.com/c/cells

We'll be happy to help you with any questions or provide you the code samples as well in our forums. Also, I'll close this issue, and you may do further follow ups in the forum mentioned above. 

I hope this helps.
