### ISSUE TITLE
Word online API to integrate in Ruby Rails Application

### ISSUE THREAD

**Issue by PriyankaMuddana** [aspose-free-consulting/projects#56]
Wanted to integrate Word online to Ruby on Rails application where our customers will upload/edit document. But, i can see words for .net, java, c but didn't find any as such for Ruby/Rails. Could someone help with this?

**Comment by bepmpro-com** [comment]
@PriyankaMuddana 

Have you tried our cloud APIs with Ruby SDK? https://products.aspose.cloud/words/ruby if not, please give it a try. You can try it with the free tier. 

Also, kindly post your questions related to the [APIs in our forums](https://forum.aspose.com/), so that our team can help you quickly and properly. Thanks for your understanding.

**Comment by shahzad-latif** [comment]
@PriyankaMuddana

Have you tried our cloud APIs with Ruby SDK? https://products.aspose.cloud/words/ruby if not, please give it a try. You can try it with the free tier.

Also, kindly post your questions related to the APIs in our forums, so that our team can help you quickly and properly. Thanks for your understanding.
