### ISSUE TITLE
I want to fill certain values in an tax return pdf which is non-fillable. Is that possible to make it fillable and then filling those values using aspose pdf library? I am using .net core 3.

### ISSUE THREAD

**Issue by veenadange** [aspose-free-consulting/projects#66]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by asadalikhan90** [comment]
@veenadange 

Aspose.PDF for .NET allows you to [fill PDF Forms (XFA/Standard Acro)](https://docs.aspose.com/pdf/net/working-with-forms/). However, if PDF does not contain any interactive/fillable fields, you can [perform text replace operation](https://docs.aspose.com/pdf/net/replace-text-in-a-pdf-document/) in order to add some value to it. In case you experience any issue, please share your sample PDF document with us along with the expected output PDF so that we can test the scenario in our environment and share our feedback with you accordingly. Also, you may please post such inquiries in the [Aspose.PDF forum](https://forum.aspose.com/c/pdf) where you can get a quicker response.
