### ISSUE TITLE
I want to create/build an application to convert DWG to DXF

### ISSUE THREAD

**Issue by PrasantaMohanty** [aspose-free-consulting/projects#69]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario : YES
* It is related to Aspose APIs                                      : YES
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by mudassirfayyaz** [comment]
@PrasantaMohanty 

Aspose.CAD API supports reading the DWG files and saving them in DXF file format. Can you please visit [this documentation link](https://docs.aspose.com/cad/net/dwg-drawings/#convert-dwg-drawings-to-dxf) that fulfills the exact requirements stated by you. If you encounter any issue while loading any DWG file or saving that as DXF, then please share with us in [official Aspose.CAD support forum](https://forum.aspose.com/c/cad) with source file/files so that we may investigate that further and log it in our issue tracking system.

**Comment by mudassirfayyaz** [comment]
@PrasantaMohanty 

We have added a small sample project for loading and DWG and saving to DXF. Please proceed to [this download link](https://drive.google.com/file/d/173TNtgYPSBp6uP6j3SaIa1Zqc6fmKJaj/view?usp=sharing) for your convenience. I hope this will be helpful to you.
