### ISSUE TITLE
An unhandled exception of type 'System.ArgumentException' occurred in Aspose.PDF.dll  Additional information:Box child can not be null

### ISSUE THREAD

**Issue by ubaid4** [aspose-free-consulting/projects#71]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by asadalikhan90** [comment]
@ubaid4 

Would you please share a bit more details about the issue that you are facing while using the API? We also suggest you, please create a post in our [support forum](https://forum.aspose.com/c/pdf) along with sample source files and sample code snippet so that the scenario can be tested and the issue can be addressed accordingly (if any).
