### ISSUE TITLE
divide ms Word document into HTML according to regular expression and font features (font-size, font-family, font-color).

### ISSUE THREAD

**Issue by shun-shiranita** [aspose-free-consulting/projects#83]
Dear Aspose,
Could I ask you to do some coding about the project below in Free consulting place? 

**Specification for division of ms Word document into HTML**

**input/output/parameters**
input: ms Word document
output: divided HTML
param: three sets of regex, font-size, font-family, font-color

**environment**
docker + Linux

**Requirements:**
It's necessary to split a ms Word document depending on three criteria i.e. section, subsection, item.
Each criterion consists of specified regex, font-size, font-family, font-color.

In the first cycle, an input document will be splitted base on the pieces of information of the "section" 
(regex, font-size, font-family, font-color).
In details, the criterion searches over a document for a string with specified regex, font-size, font-family and font-color.
If it finds a string matched, the script splits the document just before the string. 

In the second cycle, each splitted document will then divided based on the pieces of information of the "subsection" likewise.
(regex, font-size, font-family, font-color).
In the third cycle, the splitted parts in the second cycle will be divided further based on the pieces of information of the "item" in the same way.
(regex, font-size, font-family, font-color).

The final output should be forms of HTML.
What is important is never to let objects in the original document move from where they are displayed in it.
I assume that the functions above can be realized using some components of Aspose.Total.

**Comment by awaishafeez** [comment]
@shun-shiranita, 

Yes, it looks possible to meet these requirements by using [Aspose.Words for .NET](https://products.aspose.com/words/net) API. But, please note that when saving to plain HTML format, it is not always guaranteed that the Aspose.Words (and even MS Word) generated output HTML files will look exactly the same in web browsers as the input Word documents i.e. object's layout/position may alter upon saving to HTML. This is because of file format differences between Word and HTML (and [some other limitations](https://docs.aspose.com/words/net/save-in-the-html-html-xhtml-mhtml-format/)). However, Aspose.Words offers its own **HtmlFixed file format** that can guarantee high fidelity conversion to HTML. Standard Word to HtmlFixed conversion can be achieved by using following C# code:
```
Document doc = new Document("C:\\temp\\input.docx");
HtmlFixedSaveOptions htmlFixedSaveOptions = new HtmlFixedSaveOptions();
htmlFixedSaveOptions.PrettyFormat = true;
htmlFixedSaveOptions.ShowPageBorder = true;
htmlFixedSaveOptions.ExportEmbeddedImages = true;
doc.Save("C:\\temp\\20.10.html", htmlFixedSaveOptions);
```
Secondly, the standard way of finding text/string in Word document is mentioned in this article: [Find and Replace](https://docs.aspose.com/words/net/find-and-replace/). And to work with font-size, font-family and font-color, Aspose.Words provides [Font.Name](https://apireference.aspose.com/words/net/aspose.words/font/properties/name), [Font.Size](https://apireference.aspose.com/words/net/aspose.words/font/properties/size) and [Font.Color](https://apireference.aspose.com/words/net/aspose.words/font/properties/color) Properties.

Moreover, we suggest you please post your query in [Aspose.Words forum](https://forum.aspose.com/c/words/8), ZIP and attach a **simplified input Word file** and **expected output HTML files** (_against each cycle/iteration_) there for our reference. This will help us to understand the structures of your input/output files, and we will then be in a better position to provide you sample code.
