### ISSUE TITLE
How to get coordinates (top and left) for any string or token in word document 

### ISSUE THREAD

**Issue by hemantthote** [aspose-free-consulting/projects#85]
Hi,

I am attaching word document here [eSignature Test 02.docx](https://github.com/aspose-free-consulting/projects/files/5345324/eSignature.Test.02.docx). I want to find the TOP and LEFT for the all strings included in "<<>>" on word document, for ex. SIGNM01. How can i achieve it using aspose? Can you please share the required code?

Thanks in advance,
Hemant

**Comment by shahzad-latif** [comment]
@hemantthote ,

We're look into this requirement and will get back to you soon.

**Comment by shahzad-latif** [comment]
This issue was posted in forum and supported here: [How to Get Coordinates (top and left) of Text in Word Document using .NET](https://forum.aspose.com/t/how-to-get-coordinates-top-and-left-of-text-in-word-document-using-net/219600).

[A working sample can be downloaded here as well.](https://github.com/aspose-free-consulting/projects/files/5530211/TopLeftPositionOfString.zip)

**Comment by shahzad-latif** [comment]
This project can be viewed here: [Get coordinates (Top and Left) for any String or tToken in Word Document](https://github.com/aspose-free-consulting/Get-Top-and-Left-Coordinates-of-Text-in-Word-Document-in-.NET)
