### ISSUE TITLE
Java USES version 20.9 of the PDF JAR. Why only extract the first paragraph of each page?

### ISSUE THREAD

**Issue by dongsp** [aspose-free-consulting/projects#96]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by dongsp** [comment]
Attached is the PDF file that needs to be extracted.
[Uploading Tanslation_文档翻译测试文档_英到中.pdf…]()

**Comment by shahzad-latif** [comment]
@dongsp 

I believe, this is due to the trial version of the API. You can get the [temporary license for 30 days](https://purchase.aspose.com/temporary-license) and try without limitations. Also, please [post such queries in our support forums](https://forum.aspose.com/c/pdf), so we can properly help you out. Thanks.
